# echo 'source "$HOME/.config/zsh/zshrc"' >> ~/.zshrc
ZSH_CONFIG="$HOME/.config/zsh"
export ZSH="$ZSH_CONFIG/oh-my-zsh"
export ZSH_COMPDUMP="$ZSH/cache/.zcompdump-$HOST"
export ZSH_CUSTOM="$HOME/.config/zsh/custom"
export LANG=en_US.UTF-8
export EDITOR='vim'
export GPG_TTY=$(tty)
export PATH="$HOME/.local/bin:$PATH"

ZSH_THEME="fwalch"
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"

zstyle ':omz:update' mode reminder

plugins=(
    colored-man-pages
    fzf
    kubectl
    git
    mise
    zsh-autosuggestions
    zsh-syntax-highlighting
)

PROMPT_HOST=false
PROMPT_KUBE=true
PROMPT_VENV=true

source "$ZSH/oh-my-zsh.sh"
source "$ZSH_CONFIG/zsh_aliases.sh"
source "$ZSH_CONFIG/zsh_functions.sh"

# Hook to update prompt with hostname, venv, kubectl
## Doing this specially because of kubectl,
## extensions like kube-ps1 rely on kubectl config current-context, which can be slow and is network dependent
## I just want to show the current context according to my kube config file
PROMPT_BASE="$PROMPT"
autoload -Uz add-zsh-hook
add-zsh-hook precmd update_prompt

# Hook to auto activate/deactivate python virtual envs
#add-zsh-hook chpwd virtual_env_activate

# Load mise environment
if command -v mise > /dev/null; then
    eval "$(mise activate zsh)"
fi

